# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6957d2575f5c30be8c3a9233a7505163375f749ef682a573fe33a60415a33c0a5f7cd8e3df57a0b28fc121bd793ee382e97d07ffd27e87c0e169b1bc986708c

test:
  secret_key_base: 7dd234450798e391f317a88eb129c4d8a2280d2fe6c36fd33a208b1bf215541008ccf8f6c6f6cb94aab410c8c08128fa6516811de2a9a74f932eb7b3266561c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
